### ISSUE TITLE
Any idea for support small pieces of diray?

### ISSUE THREAD

**Issue by puppylpg** [PhiTux/DailyTxT#11]
Thanks for your work. I really like it. 

There is only one text area to write for one day now. Any ideas to support posting many ideas in a day and show them one piece by one piece?

Your work really excites me! Thanks again.

**Comment by PhiTux** [comment]
Thank you :)
I'm just wondering why there is (as far as I know) NO SINGLE comparable software out there...

I understand your idea and intention with those multiple (small) posts for each day (since you experience different things at one day, and every thing might earn an individual representation). 
But I do not want to change the base-idea of DailyTxT of just having a single plaintext-area for each day. So I'm sorry, but this feature will not come with DailyTxT. 
I want to keep DailyTxT as simple and transferable to possible new developments in the future as possible.

You will have to deal with this single text-area and you can use empty lines to separate ideas or events.
