### ISSUE TITLE
Improvement: text templates

### ISSUE THREAD

**Issue by JackHewson** [PhiTux/DailyTxT#12]
**Please consider to add the possibilty to add text templates.**
I want to answer a bunch of questions to myself each day, and I want to autofill them.

(Thank you for this project! I like it very much because it's self-hosted, responsive and encrypted.)

**Comment by PhiTux** [comment]
Thanks.

Could you please go more into detail what you mean by "autofilling" the questions?

The thing is: I do not want to (/ will not) change the basic layout, where ONLY plaintext is saved. I want to keep it simple.
There will not be coming a feature like some flexible layout, where only a bunch of (flexible) input fields are left.

**Comment by JackHewson** [comment]
I use your software to answer myself a bunch of questions everyday.
Now I copy manually these questions each day to the input form, but I want to setup a template, which fills it automatically (or on demand).

Thanks!

**Comment by PhiTux** [comment]
Thanks for clarifying.

I can imagine providing a feature that inserts any template on demand (on clicking a button). 

I think this is a good idea.

However, it will take a few weeks to months until such a feature comes, because I would combine that with a complete revision of the settings (the settings will get their own menu instead of multiple pop-ups).

**Comment by kernelkaribou** [comment]
I think this is a great idea, some kind of template builder (or just upload a plain text template ) that could be encrypted and treated almost the same as an entry.  Have some kind of drop down/selection menu that lets you pick a template that fills in the entry.   Possibly to the right of the last edited tab to use that white space if possible. Additionally could be smart enough if there is any entries in the journal already to just append the template assuming someone would otherwise clear out the entry for the day before using a template.

**Comment by PhiTux** [comment]
See new version 1.0.10 😉
