### ISSUE TITLE
Cannot export data

### ISSUE THREAD

**Issue by Lemon553311-dev** [PhiTux/DailyTxT#17]
Hello! I have run into a problem with DailyTxT. When trying to export data it just simply doesn't
I have tried:

- Restarting docker contrainer (assuming it's done in ``docker restart dailytxt`` way)
- Logging out and logging in
- Different browser 
- Do it on mobile (in fact I left it "trying" to export for a good 5-7 minutes no reaction.)

I am not really sure what to do other than contact here. I feel really unsafe without a backup. Don't wanna lose all my entries you know. Thanks in advance!

**Comment by PhiTux** [comment]
1. Do you still see all your postings of each day? (So are you correctly logged in?)

2. The Export-time strongly depends on the amount of uploaded files! If you only have text, then the export is instant. If you have just uploaded a few files (like about 10 Photos), then it will already take several seconds. Having a lot of uploaded Photos/Files might actually take several seconds. 
Sadly there is no possibility to get any progress-bar of the export at the moment... 

3. As long as you see your postings everything is fine and your data is not corrupted! In this case it is probably 'just' an error in the export. But in this case you can simply "backup" your data by making a backup of the data-volume/-folder and make sure to save the user/password-combination

**Comment by Lemon553311-dev** [comment]
It really is just 10 (a bit more) photos and videos there. Seems like some error. I'll follow your 3 recommendation to backup the folder. :/

**Comment by Lemon553311-dev** [comment]
Would be really nice to somehow report the bug if your app had some way to view an error dump

**Comment by PhiTux** [comment]
Sadly there isn't a really good possibility to view an error dump. 
The only two ways to get a little bit more information are probably the following:
a) Take a look at the browser "console" and the "network analysis" tabs while exporting. Perhaps there are more details visible in the POST-response when trying to export.
b) You could try to view the docker logs. Either by `docker logs dailytxt` or by connecting into the running container (to do this first run `docker exec -it dailytxt /bin/sh` and then view the nginx-logs e.g. by running `cat /var/log/nginx/error.log`).

---

And secondly, for test-reasons you could perhaps try the following:

1. Make a backup of your data-folder!
2. Download and **delete** (!) the few files that you uploaded. Especially the video-uploads. (I'm wondering a bit that you uploaded video-files. How big are those files? The maximum-size of uploads should be limited to 128 MB.)
3. Try to make an export again (now without the files). If it's working, then you know that the files produced the errors. 

In case you did those steps: please post the results here, since I'm interested in the reason of your error as well...

**Comment by Lemon553311-dev** [comment]
## Errors and traceback
Unfortunately I didn't get really valued errors here
**Console did tell me a bit here's what happend:**
```
xhr.js:184          POST http://(my website IP)/api/exportData 500 (INTERNAL SERVER ERROR)
Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at f.onreadystatechange (xhr.js:69:7)
```

![image](https://user-images.githubusercontent.com/60439353/210139555-8f34cd7e-0b54-49de-8a5b-16ae82f76730.png)
(couldn't copy it)

**``sudo docker logs dailytxt`` **returns nothing.**** 

NGINX log has a lot of (probably not helpful) warnings. I assume it happens when I try to download many files at once?
```
[warn] 20#20: *6245 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/5/03/0000000035 while reading upstream, client: (MY IP), server: , request: "POST /api/downloadFile HTTP/1.1", upstream: "http://127.0.0.1:5000/api/downloadFile", host: "(SERVER IP)", referrer: "http://(SERVER IP)/"
```
Another "unique" thing is this:
``[emerg] 21#21: io_setup() failed (38: Function not implemented)``

## Testing
**I have tried exporting data with no files and nothing happened
Testing returned same errors in console (browser console)
There were no errors in ``docker logs`` nor nginx error logs.**
## My idea of the error
1. There's a possibility it is a problem in my processor on my server. (aarch64)
Since it refused to run because of my processor I used a "hacky?" way to run it using  ``--platform=linux/amd64`` in my pleaserun.sh script file
According to dailytxt docker page [https://hub.docker.com/r/phitux/dailytxt/tags](this) it only supports amd64 while I have aarch64 (``lscpu``)
Not sure if it's source of the problem
2. My writing in dailytxt is NOT english and it somehow errors?

That's pretty much it what I could find
I hope this helps a bit. I'll stick to copying my data folder in case something terrible happens

**Comment by PhiTux** [comment]
Thanks very much for your detailed answer!
Actually directly the first information says 'enough', since it's an error 500, which means, that it is an internal error on the server and so it finished the export with an error. Sadly at this point it's still not possible to get a more detailed idea, what exactly is the reason for this error. 
Normally I would now presume, that It's a bug in dailytxt. But thanks for your information about your processor architecture! Since exactly this export needs more interaction with the filesystem and the OS it is absolutely possible that this is the source of your problems! 
Dailytxt is definitely just made to run on `amd64` and not on ARM... I have no support for other platforms! 

The only way that I see: you could try to create you own docker-image for your platform... Clone the repo and create the image by running `docker build .`


The language you write in is not important! You probably just mean the syntax-checking? You could try to disable it (some browsers allow this)

**Comment by Lemon553311-dev** [comment]
> The only way that I see: you could try to create you own docker-image for your platform... Clone the repo and create the image by running `docker build .`

Oh no not again. I guess I'll just resort to copying the folder for now. That thing is torture!! I built the image, tagged it and docker can't find it anyway :/ I'll pass

Little question: When running the container with docker run there's a variable SECRET_KEY with a bunch of random characters. Does it play a role in accessing my data? (So I would need to back it up aswell)

**Comment by PhiTux** [comment]
Well, `aarch64` is probably not a lot of fun...

No, the SECRET_KEY is only necessary to be able to **stay logged in** to your current session when restarting the docker container! You can always access your data as long as you know your username+password (and/or backup-keys)!
