### ISSUE TITLE
Feature Idea - Random/ Generated Prompts

### ISSUE THREAD

**Issue by Monsterray** [PhiTux/DailyTxT#28]
I would like to see a way to have prompts be given to users. Something like a way to randomly chose from a list of prompts to be given to users each day. Also have it as an option per user or be set server wide.

**Comment by PhiTux** [comment]
Thanks @h3x0x0,
that's what I thought :D 

Just to be sure: @Monsterray you mean something like generated prompts by an AI like ChatGPT, right?
I will definitely NOT write such a feature by myself. First because I don't feel like it's needed. Does an AI know what happened that day? And second because this would somehow overload the otherwise minimal DailyTxT (and third I can right now absolutely not foresee the effort to write such a feature - while my time is limited).
