### ISSUE TITLE
Automatic (decrypted?) backups?

### ISSUE THREAD

**Issue by TheNomad11** [PhiTux/DailyTxT#35]
Is it possible to make automatic backups and decrypt the content at the same time?
I really like this app and like to use it more. But with diary applications it is especially important that the content will be safe for a long time. 

I know that I can export the data from the web interface, but can it be automated in some way? 

Of course I could just back up the docker volume with the json files, but they are encrypted, so I suppose the content can only be read by the dailytxt itself? 

Thanks for the great software!

**Comment by PhiTux** [comment]
Hi (probably my fastest reply ever 😅)
basically a good idea, I see your intention, but I see several problems. 
Saving an automatic decrypted backup doesn't really make sense, since the idea of dailytxt is, to save the data **en**crypted on the server storage. Mainly because dailytxt supports multiple users and the server admin shall **not** be able to read the content of other users.
Then there is a technical problem, that the server backend would have to save the encryption key / password for making automatic backups at any time. At the moment the server does **not** save the (readable) encryption key but gets it for each user's action from the user's request.

I absolutely understand your point, that this content has a very special importance. But right now I don't see a useful way to implement this. Strict encryption of journal/diary-data on the server-side has a strong/stronger relevance for me right now.

As you say: at the moment the best way to do backups is the "normal" linux-server-way to backup the json-files. Keeping the docker images is a good additional idea. As I use dailytxt regularly myself it should have long support including upgrade-support to newer version (in case this happens in the next years).

**Comment by TheNomad11** [comment]
Thanks so much for your quick and helpful answer!

Regarding the json files I have a noob question: If I back them up, is it possible to decrypt them without daailytxt by some linux commands and my password?

**Comment by TheNomad11** [comment]
Cool, thanks a lot, good to hear!

**Comment by PhiTux** [comment]
Hey @TheNomad11 
I have just written a separate tool in rust, which addresses this (very important) feature.
It's here: https://github.com/PhiTux/dailytxt-decrypt-cli 
Now you can just normally backup your encrypted (!) json-files (e.g. by using rsync) and then you can always decrypt all logs and print them into easily readable txt-files. You just have to remember your password or backup-codes ;)

**Comment by TheNomad11** [comment]
Thanks a lot! there is an error in the documentation, though. I will file a bug report
